import type { Metadata } from "next";
import {Rock_3D, Geist, Geist_Mono, Poppins, Roboto} from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/navbar";
import Footer from "@/components/footer/footer";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const roboto = Roboto({
  variable: "--font-roboto-sans",
  subsets: ["latin"],
});

const rock = Rock_3D({
  variable: "--font-rock-3d",
  weight: '400',
  subsets: ["latin"],
})

const poppins = Poppins({
  variable: "--font-poppins-sans",
  weight: ['400', '700'],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
                                     children,
                                   }: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="en">
      <body className={`${rock.variable} ${rock.variable}`}>
      <div className= "container" style={{
          display: "flex",
          flexDirection: "column",
      }}>
        <Navbar/>
        {children}
        <Footer/>
      </div>
      </body>
      </html>
  );
}

